# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\PokerChanceCalculator\Deck\Provider:
        arguments:
            - '@App\PokerChanceCalculator\Deck\Source\Session'
            - '@App\PokerChanceCalculator\Deck\Source\Untouched'
    App\PokerChanceCalculator\Manager:
        arguments:
            $deckProvider: '@App\PokerChanceCalculator\Deck\Provider'
    App\PokerChanceCalculator\Deck\Source\Untouched:
        arguments:
            $suits:
                - '@App\PokerChanceCalculator\Suit\Clubs'
                - '@App\PokerChanceCalculator\Suit\Diamonds'
                - '@App\PokerChanceCalculator\Suit\Hearts'
                - '@App\PokerChanceCalculator\Suit\Spades'
            $ranks:
                - '@App\PokerChanceCalculator\Rank\Ace'
                - '@App\PokerChanceCalculator\Rank\Two'
                - '@App\PokerChanceCalculator\Rank\Three'
                - '@App\PokerChanceCalculator\Rank\Four'
                - '@App\PokerChanceCalculator\Rank\Five'
                - '@App\PokerChanceCalculator\Rank\Six'
                - '@App\PokerChanceCalculator\Rank\Seven'
                - '@App\PokerChanceCalculator\Rank\Eight'
                - '@App\PokerChanceCalculator\Rank\Nine'
                - '@App\PokerChanceCalculator\Rank\Ten'
                - '@App\PokerChanceCalculator\Rank\Jack'
                - '@App\PokerChanceCalculator\Rank\Queen'
                - '@App\PokerChanceCalculator\Rank\King'
    App\PokerChanceCalculator\Rank\Builder:
        arguments:
            $availableRanks:
                !php/const App\PokerChanceCalculator\RankInterface::ACE: '@App\PokerChanceCalculator\Rank\Ace'
                !php/const App\PokerChanceCalculator\RankInterface::TWO: '@App\PokerChanceCalculator\Rank\Two'
                !php/const App\PokerChanceCalculator\RankInterface::THREE: '@App\PokerChanceCalculator\Rank\Three'
                !php/const App\PokerChanceCalculator\RankInterface::FOUR: '@App\PokerChanceCalculator\Rank\Four'
                !php/const App\PokerChanceCalculator\RankInterface::FIVE: '@App\PokerChanceCalculator\Rank\Five'
                !php/const App\PokerChanceCalculator\RankInterface::SIX: '@App\PokerChanceCalculator\Rank\Six'
                !php/const App\PokerChanceCalculator\RankInterface::SEVEN: '@App\PokerChanceCalculator\Rank\Seven'
                !php/const App\PokerChanceCalculator\RankInterface::EIGHT: '@App\PokerChanceCalculator\Rank\Eight'
                !php/const App\PokerChanceCalculator\RankInterface::NINE: '@App\PokerChanceCalculator\Rank\Nine'
                !php/const App\PokerChanceCalculator\RankInterface::TEN: '@App\PokerChanceCalculator\Rank\Ten'
                !php/const App\PokerChanceCalculator\RankInterface::JACK: '@App\PokerChanceCalculator\Rank\Jack'
                !php/const App\PokerChanceCalculator\RankInterface::QUEEN: '@App\PokerChanceCalculator\Rank\Queen'
                !php/const App\PokerChanceCalculator\RankInterface::KING: '@App\PokerChanceCalculator\Rank\King'
    App\PokerChanceCalculator\Suit\Builder:
        arguments:
            $availableSuits:
                !php/const App\PokerChanceCalculator\SuitInterface::CLUBS: '@App\PokerChanceCalculator\Suit\Clubs'
                !php/const App\PokerChanceCalculator\SuitInterface::DIAMONDS: '@App\PokerChanceCalculator\Suit\Diamonds'
                !php/const App\PokerChanceCalculator\SuitInterface::HEARTS: '@App\PokerChanceCalculator\Suit\Hearts'
                !php/const App\PokerChanceCalculator\SuitInterface::SPADES: '@App\PokerChanceCalculator\Suit\Spades'
    App\PhraseAnalyser\Statistics\Provider:
        arguments:
            - '@App\PhraseAnalyser\Statistics\CharOccurrences'
            - '@App\PhraseAnalyser\Statistics\CharSiblings'
            - '@App\PhraseAnalyser\Statistics\MaxDistanceBetweenChars'
    App\PhraseAnalyser\Manager:
        arguments:
            $statisticsProvider: '@App\PhraseAnalyser\Statistics\Provider'